Add setter + various fixes
ArrowSphere/catalog-graphql-client pull request #16
Opened 2021-03-21 10:39 UTC by william-kalvarisky

2021-03-22 15:28 UTC, pfeyssaguet requested changes

2021-03-22 15:28 UTC, pfeyssaguet commented on src/Types/Filters.php
> + * @method Filters setValue(FiltersValues[] $values)
setValues()

2021-03-22 15:28 UTC, pfeyssaguet commented on src/Types/PaginatedProducts.php
> + * @method PaginatedProducts setFilters(Filters[] $filter)
$filters

2021-03-22 15:28 UTC, pfeyssaguet commented on src/Types/ActionFlags.php
> + * @method ActionFlags setRenewalSku(bool $isRenew)
$renewalSku

2021-03-22 15:28 UTC, pfeyssaguet commented on src/Types/ArrowsphereIdentifier.php
> + * @method ArrowsphereIdentifier setOrderableSku(string $OrderableSku)
$orderableSku

2021-03-22 15:28 UTC, pfeyssaguet commented on src/Types/Program.php
> + * @method Program setNames(ProgramName $name)
$names

2021-03-22 15:28 UTC, pfeyssaguet commented on src/Types/Uom.php
> + * @method Uom setQuantity(int $qty)
$quantity

2021-03-23 07:08 UTC, william-kalvarisky commented on src/Types/Filters.php
> + * @method Filters setValue(FiltersValues[] $values)
done

2021-03-23 07:08 UTC, william-kalvarisky commented on src/Types/PaginatedProducts.php
> + * @method PaginatedProducts setFilters(Filters[] $filter)
done

2021-03-23 07:08 UTC, william-kalvarisky commented on src/Types/ActionFlags.php
> + * @method ActionFlags setRenewalSku(bool $isRenew)
done

2021-03-23 07:08 UTC, william-kalvarisky commented on src/Types/Program.php
> + * @method Program setNames(ProgramName $name)
done

2021-03-23 07:08 UTC, william-kalvarisky commented on src/Types/Uom.php
> + * @method Uom setQuantity(int $qty)
done

2021-03-23 10:25 UTC, pfeyssaguet approved these changes

2021-03-23 10:25 UTC, pfeyssaguet commented on src/Types/Filters.php
>      public const VALUE = 'value';
This const can be removed now, no?

2021-03-23 15:20 UTC, merged